name: Android CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action to run"
        required: true
        type: choice
        options:
          - lint
          - test
          - build

jobs:
  lint:
    if: ${{ github.event.inputs.action == 'lint' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew lintDebug --stacktrace

  test:
    if: ${{ github.event.inputs.action == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew testDebugUnitTest --stacktrace

  build:
    if: ${{ github.event.inputs.action == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
